sudo: false
language: python
python:
- '2.7'
branches:
  only:
  - master
git:
  depth: 10
before_install:
- openssl aes-256-cbc -K $encrypted_1645300b04d0_key -iv $encrypted_1645300b04d0_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- tail -n +3 app.yaml > app.yaml.new && mv app.yaml.new app.yaml && cat app.yaml
- pip install -r requirements.txt -t lib
install: true
script: true
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: service_account.json
  project: vjcblazer
  on: master
