sudo: false
language: python
python:
  - "2.7"
branches:
  only:
    - master
git:
  depth: 10
before_install:
- openssl aes-256-cbc -K $encrypted_9a7242d4f9d5_key -iv $encrypted_9a7242d4f9d5_iv
  -in 420blazeit.json.enc -out 420blazeit.json -d
install: true
script: true
deploy:
  provider: gae
  keyfile: 420blazeit.json
  project: 420blazeit
  on: master
