sudo: false
language: python
python:
- '2.7'
branches:
  only:
  - master
git:
  depth: 10
before_install:
- tail -n +3 app.yaml > app.yaml.new && mv app.yaml.new app.yaml && cat app.yaml
- openssl aes-256-cbc -K $encrypted_1645300b04d0_key -iv $encrypted_1645300b04d0_iv
  -in 420blazeit.json.enc -out 420blazeit.json -d
install: true
script: true
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: 420blazeit.json
  project: vjcblazer
  on: master
