application: 420blazeit
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /resources
  static_dir: public/resources

- url: /
  script: app.home
  secure: always

- url: /(loaned|available)
  script: app.listings
  secure: always
  login: admin

- url: /blazer/.*
  script: app.blazer
  secure: always
  login: required

- url: /favicon\.ico
  static_files: public/favicon.ico
  upload: public\/favicon\.ico

- url: /robots\.txt
  static_files: public/robots.txt
  upload: public\/robots\.txt

- url: /.*
  script: app.oauth
  secure: always
  login: required

error_handlers:
  - file: templates/error.html

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest

- name: markupsafe
  version: latest
